version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_BACKEND
      - DB_DSN
    ports:
      - "9000:9000"
  mysql:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ~/data/docker/mysql_dev:/var/lib/mysql:rw